apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: nr-isd-exp-ss1
spec:
  duration: 6m
  templates:
  - name: baseline
    selector:
      matchLabels:
        app: nr-exp-app1
    template:
      metadata:
        labels:
          app: nr-exp-app1
      spec:
        containers:
        - name: baseline
          image: quay.io/opsmxpublic/canary-issuegen:issue-canary-gen-1402
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
            - name: NEWRELIC_LICENSE
              value: 68b87ee3618f714a039cead822d6d250b54dNRAL
            - name: SERVICE_NAME
              value: issuegen-exp-ss1-app1
  - name: canary
    selector:
      matchLabels:
        app: nr-exp-app2
    template:
      metadata:
        labels:
          app: nr-exp-app2
      spec:
        containers:
        - name: canary
          image: quay.io/opsmxpublic/canary-issuegen:issue-canary-gen-1402
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
            - name: NEWRELIC_LICENSE
              value: 68b87ee3618f714a039cead822d6d250b54dNRAL
            - name: SERVICE_NAME
              value: issuegen-exp-ss1-app2
  analyses:
  - name: analysis-isd-for-nr-exp
    requiredForCompletion: true
    templateName: analysis-isd-for-nr-exp
    args:
    - name: start-time
      value: "{{experiment.availableAt}}"
    - name: end-time
      value: "{{experiment.finishedAt}}"
    - name: baseline-hash
      value: "{{templates.baseline.podTemplateHash}}"
    - name: canary-hash
      value: "{{templates.canary.podTemplateHash}}"
