kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: isd-analysis-bg-v1
spec:
  args:
    - name: preview-hash
    - name: baseline-hash
    - name: servicename
  metrics:
    - name: isd-analysis-bg-v1
      count: 1
      initialDelay: 120s
      provider:
        opsmx:
          application: isd411
          user: admin
          lifetimeMinutes: 3
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: "{{args.servicename}}"
            metricTemplateName: prometheus-health-validator
            metricTemplateVersion: "v2.0"
            metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "isd411,.*{{args.baseline-hash}}.*,oes" 
            canaryMetricScope: "isd411,.*{{args.preview-hash}}.*,oes"
