apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    app.kubernetes.io/managed-by: Helm
    chart: isdargo-4.1.0
    component: auditclient
    heritage: Helm
    release: isd411
  name: oes-audit-client-preview
spec:
  clusterIP: 10.51.254.252
  clusterIPs:
  - 10.51.254.252
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: auditclient
    port: 8098
    protocol: TCP
    targetPort: 8098
  selector:
    app: oes
    component: auditclient
  sessionAffinity: None
  type: ClusterIP
