apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    app.kubernetes.io/managed-by: Helm
    chart: isdargo-4.1.0
    component: autopilot
    heritage: Helm
    release: isd411
  name: oes-autopilot-stable
spec:
  ports:
  - name: cas-service
    port: 8090
    protocol: TCP
    targetPort: 8090
  - name: monitoring-service
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: oes
    component: autopilot
  sessionAffinity: None
  type: ClusterIP
