apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
metadata:
  name: oes-autopilot
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: argo-in-dev-process
    notifications.argoproj.io/subscribe.on-rollout-aborted.slack: argo-in-dev-process
    notifications.argoproj.io/subscribe.on-analysis-run-failed.slack: argo-in-dev-process
    notifications.argoproj.io/subscribe.on-analysis-run-error.slack: argo-in-dev-process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: autopilot
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: oes-autopilot
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: oes-autopilot-stable
      previewService: oes-autopilot-preview
      prePromotionAnalysis:
        templates:
        - templateName: isd-analysis-bg-v1
        args:
        - name: baseline-hash
          valueFrom:
            podTemplateHashValue: Stable
        - name: preview-hash
          valueFrom:
            podTemplateHashValue: Latest
        - name: servicename
          valueFrom: 
            fieldRef:
              fieldPath: metadata.name
