apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    app.kubernetes.io/managed-by: Helm
    chart: isdargo-4.1.0
    component: datascience
    heritage: Helm
    release: isd411
  name: oes-datascience
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: oes
      component: datascience
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        configmap/checksum: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
        prometheus.io/scrape: "false"
        prometheus_io_path: /mgmt/prometheus
        prometheus_io_port: "5005"
      creationTimestamp: null
      labels:
        app: oes
        chart: isdargo-4.1.0
        component: datascience
        heritage: Helm
        release: isd411
    spec:
      containers:
      - image: quay.io/opsmxpublic/ubi8-oes-datascience:v4.1.1-rc1
        imagePullPolicy: IfNotPresent
        name: oes-datascience
        ports:
        - containerPort: 5005
          name: backend
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5005
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/ubuntu/.aws/credentials
          name: datascience-config-volume
          subPath: minio-credentials
        - mountPath: /home/ubuntu/datascience/app_config.yaml
          name: datascience-config-volume
          subPath: app-config.yml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: opsmx11-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: datascience-config-volume
        secret:
          defaultMode: 420
          secretName: oes-datascience-config
