apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    app.kubernetes.io/managed-by: Helm
    chart: isdargo-4.1.0
    component: datascience
    heritage: Helm
    release: isd411
  name: oes-datascience-preview
spec:
  clusterIP: 10.51.251.183
  clusterIPs:
  - 10.51.251.183
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: datascience
    port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: oes
    component: datascience
  sessionAffinity: None
  type: ClusterIP

