apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    app.kubernetes.io/managed-by: Helm
    chart: isdargo-4.1.0
    component: datascience
    heritage: Helm
    release: isd411
  name: oes-datascience-stable
spec:
  ports:
  - name: datascience
    port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: oes
    component: datascience
  sessionAffinity: None
  type: ClusterIP

