apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
metadata:
  name: oes-datascience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: datascience
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: oes-datascience
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: oes-datascience-stable
      previewService: oes-datascience-preview
      prePromotionAnalysis:
        templates:
        - templateName: isd-analysis-bg-v1
        args:
        - name: baseline-hash
          valueFrom:
            podTemplateHashValue: Stable
        - name: preview-hash
          valueFrom:
            podTemplateHashValue: Latest
        - name: servicename
          valueFrom: 
            fieldRef:
              fieldPath: metadata.name
