apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    app.kubernetes.io/managed-by: Helm
    chart: isdargo-4.1.0
    component: gate
    heritage: Helm
    release: isd411
  name: oes-gate-preview
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8084
  - name: oes-gate-service
    port: 8084
    protocol: TCP
    targetPort: 8084
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8084
  selector:
    app: oes
    component: gate
  sessionAffinity: None
  type: ClusterIP
