apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: isd411
    meta.helm.sh/release-namespace: isd411
  labels:
    app: oes
    app.kubernetes.io/managed-by: Helm
    chart: isdargo-4.1.0
    component: platform
    heritage: Helm
    release: isd411
  name: oes-platform
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: oes
      component: platform
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus_io_path: /mgmt/prometheus
        prometheus_io_port: "8095"
      labels:
        app: oes
        chart: isdargo-4.1.0
        component: platform
        heritage: Helm
        release: isd411
    spec:
      containers:
      - image: docker.io/opsmx11/oes-platform:4bd0469c-1933
        #docker.io/opsmx11/oes-platform:4bd0469c-1933
        #quay.io/opsmxpublic/ubi8-oes-platform:v4.1.1-rc1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /mgmt/health
            port: 8095
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: oes-platform
        ports:
        - containerPort: 8095
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8095
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opsmx/conf/platform-local.yml
          name: platform-config-volume
          subPath: platform-local.yml
        - mountPath: /opsmx/conf/bootstrap.yml
          name: bootstrap-config-volume
          subPath: bootstrap.yml
        - mountPath: /opsmx/conf/standard-error-code.csv
          name: standard-error-conf
          subPath: standard-error-codes.csv
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: opsmx11-secret
      initContainers:
      - command:
        - /bin/bash
        - -c
        - sleep 30;echo Waiting for oes-db to be up and running; pg_isready -h oes-db
          -p 5432 && echo PostgreSQL DB is ready to receive connections
        image: quay.io/opsmxpublic/postgres:9.6.5
        imagePullPolicy: IfNotPresent
        name: db-check
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: platform-config-volume
        secret:
          defaultMode: 420
          secretName: oes-platform-config
      - name: bootstrap-config-volume
        secret:
          defaultMode: 420
          items:
          - key: bootstrap.yml
            path: bootstrap.yml
          secretName: bootstrap
      - configMap:
          defaultMode: 420
          items:
          - key: standard-error-codes.csv
            path: standard-error-codes.csv
          name: standard-error-codes-config
        name: standard-error-conf
