apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
metadata:
  name: oes-sapor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: sapor
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: oes-sapor
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: oes-sapor-stable
      previewService: oes-sapor-preview
      prePromotionAnalysis:
        templates:
        - templateName: isd-analysis-bg-v1
        args:
        - name: baseline-hash
          valueFrom:
            podTemplateHashValue: Stable
        - name: preview-hash
          valueFrom:
            podTemplateHashValue: Latest
